/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tugas02;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Font;

/**
 *
 * @author LXSCOM
 */
public class truk extends javax.swing.JFrame {
    int p = 800;
    int l = 600;
    int x0 = p/2, y0 = l/2;
    int a = 0;
    int b = 0;
    Graphics g;

    /**
     * Creates new form truk
     */
    public truk() {
        initComponents();
        setSize(p,l);
        setTitle("TRUK");
        setLocationRelativeTo(null);
        this.getContentPane().setBackground(Color.white);
    }
    public void truk(){
        g = getGraphics();
        g.setColor(Color.black);//membuat moncong truk
        g.fillRect(a+x0-135, y0-(b+72), 20, 40);
        g.setColor(Color.yellow);//membuat kepala truk;
        g.fillRect(x0+a-230, y0-(b+130), 100, 100);
        g.setColor(Color.white);//membuat jendela kaca
        g.fillRect(a+x0-210, y0-(b+120), 50, 40);
        g.setColor(Color.green);//membuat bak truk
        g.fillRect(a+x0-400, y0-(b+140), 170, 110);
        g.setColor(Color.black);//membuat ban truk
        g.fillOval(a+x0-385, y0-(b+55), 60, 60);
        g.fillOval(a+x0-215, y0-(b+55), 60, 60);
        g.setColor(Color.red);//membuat velg truk
        g.fillOval(x0+a-375, y0-(b+45), 40, 40);
        g.fillOval(x0+a-205, y0-(b+45), 40, 40);
    }
    public void hapus(){
        g.setColor(Color.white);
        g.fillRect(a+x0-135, y0-(b+72), 20, 40);
        g.setColor(Color.white);
        g.fillRect(x0+a-230, y0-(b+130), 100, 100);
        g.setColor(Color.white);
        g.fillRect(a+x0-210, y0-(b+120), 50, 40);
        g.setColor(Color.white);
        g.fillRect(a+x0-400, y0-(b+140), 170, 110);
        g.setColor(Color.white);
        g.fillOval(a+x0-385, y0-(b+55), 60, 60);
        g.fillOval(a+x0-215, y0-(b+55), 60, 60);
        g.setColor(Color.white);
        g.fillOval(x0+a-375, y0-(b+45), 40, 40);
        g.fillOval(x0+a-205, y0-(b+45), 40, 40);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tampilkan = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jalankan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tampilkan.setText("Truk");
        tampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilkanActionPerformed(evt);
            }
        });

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        jalankan.setText("Jalankan");
        jalankan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jalankanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tampilkan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                .addComponent(reset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jalankan)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tampilkan)
                    .addComponent(reset)
                    .addComponent(jalankan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilkanActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tampilkanActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        repaint();
        a=0;
        b=0;
    }//GEN-LAST:event_resetActionPerformed

    private void jalankanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jalankanActionPerformed
        // TODO add your handling code here:
        while(a<200){
            try {
                truk();
                Thread.sleep(50);
                hapus();
                a+=5;
            }catch (Exception e){
                
            }
        }
        while (b>-250){
            try{
                truk();
                Thread.sleep(50);
                hapus();
                b-=3;
            }catch (Exception e){
            }
        }
        while(a<500){
            try {
                truk();
                Thread.sleep(50);
                hapus();
                a+=5;
            }catch (Exception e){
                System.out.println("error");
            }
        }
    }//GEN-LAST:event_jalankanActionPerformed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(truk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(truk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(truk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(truk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new truk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jalankan;
    private javax.swing.JButton reset;
    private javax.swing.JButton tampilkan;
    // End of variables declaration//GEN-END:variables
}
